from database import get_all_flows, save_scores

flows = get_all_flows()


# Measures how frequently a flow is used.
# It is calculated by normalizing the Run Count value to a 0–100 scale.
# Flows with higher execution frequency receive higher scores. 

flows["Usage Score"] = (
    flows["Run Count"] /flows["Run Count"].max()) * 100
#--------------------------------------------------------------

# Measures the operational risk of a flow.
# It is calculated based on the Error Rate.

flows["Risk Score"] = (flows["Error Rate"] * 10).clip(upper=100)
#----------------------------------------------------------------


# Measures the amount of manual work eliminated by automation.
# It is calculated by normalizing the Manual Time value.
# Flows that save more manual effort receive higher scores.

flows["Time Saving Score"] = (flows["Manual Time"] / flows["Manual Time"].max()) * 100

#---------------------------------------------------------------------------------


# Measures the potential of reusing or selling the automation
# to multiple customers.
# It is calculated using the Customer Count normalized to a 0–100 scale.

flows["Resell Score"] = (flows["Customer Count"] / flows["Customer Count"].max()) * 100


#--------------------------------------------------------------------------------------


# Measures how suitable a flow is for productization.
# It combines usage, reusability, and business value while considering risk.
# Higher scores indicate stronger candidates for reusable products.

flows["Product Score"] = (flows["Usage Score"] * 0.6 + flows["Resell Score"] * 0.4)

#------------------------------------------------------------------------------------


# Measures the overall business value generated by a flow.
# It combines transaction volume, time savings, and usage frequency.
# Higher scores indicate automations that create greater business impact.

flows["Business Impact"] = (
    flows["Transaction Volume"] * 0.6 +
    flows["Time Saving Score"] * 0.4
)


#-----------------------------------------------------------------------------------

# Measures how critical a flow is to business operations.
# It combines transaction volume, usage frequency, and operational risk.
# Higher scores indicate flows that require higher monitoring priority.

flows["Criticality Score"] = (
    flows["Transaction Volume"] * 0.5 +
    flows["Usage Score"] * 0.5
)

#--------------------------------------------------------------------------------------- 

# Measures the overall opportunity of a flow.
# It combines usage, product potential, business impact,
# and subtracts operational risk.
# Higher scores indicate the best candidates for expansion,
# productization, or future investment.


flows["Opportunity Score"] = (
    flows["Usage Score"] * 0.30 +
    flows["Transaction Volume"] * 0.25 +
    flows["Product Score"] * 0.30 +
    flows["Time Saving Score"] * 0.15 -
    flows["Risk Score"] * 0.20
)

#------------------------------------------------------------------------------------------- 

score_df = flows[
    [
        "Flow Name",
        "Capability",
        "Usage Score",
        "Transaction Volume",
        "Risk Score",
        "Time Saving Score",
        "Resell Score",
        "Business Impact",
        "Criticality Score",
        "Product Score",
        "Opportunity Score"
    ]
]

save_scores(score_df)

